# Theme Antarctica
#
# Stylish and feature-rich theme for Jekyll
# 
# Website: https://github.com/SdtElectronics/jekyll-theme-antarctica
#
# See the LICENCE file.
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you
# use 'bundle exec jekyll serve'. If you change this file, please restart
# the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mexa | Entrepreneurs that code
email: viava@revelion.la
author: Rebelion Labs

# Copyright setting
# You can use any html code, currently below placeholders are available:
# * current year: {currentYear}
# * author: {author} (Value is the same as site.author)
# * copyright: (c) - ©
# * copyleft: (cleft)
# * sound recording copyright: (p) - ℗ 
#
# For example:
#   "Copyright (c) 2017-{currentYear} <a href="https://example.com">{author}</a>"
#   "Copyright © 2017-2021 Foobar"
#
copyright: "{currentYear} {author}"

description: >- # this means to ignore newlines until "baseurl:"
   Mexa can be translated from Maltese to "make progress",
   "to follow someone else steps", then, here you will find guides 
   on how to create different tools for your day to day activities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/assets/img/favicon/favicon.ico" # the favicon for your site
#avatar: ""

template:
# date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %d, %Y"
  widgets: colophon comment global_cmt post_meta share related_sites table_of_content global_contact
  portfolios: projects #gallery
  propIcons:
    pinned: "&#x1f4cc;&#xFE0E;"

# If you want to generate website sitemap, you can set true
# sitemap: false

# Valine Comments
#valine:
#  appId: "GoHOdR14a6Qubobq68emQ8n2-MdYXbMMI"
#  appKey: "SCxcdTzApt8RXJVrtqsDXay0"
#  serverURLs: https://gohodr14.api.lncldglobal.com


permalink: /:title
collections_dir: collections
collections:
  helmee:
    output: true
    permalink: /:collection/:title
  kexal:
    output: true
    permalink: /:collection/:title
  projects:
    output: false
    permalink: /:collection/:title
  gallery:
    output: false
    permalink: /:collection/:title
  
projects_categories: 
  - Helmee
  - Kexal

related_sites:
  Source Repo | Rebelion Labs: https://github.com/la-rebelion
  Homepage | Rebelion Labs: https://rebelion.la/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      avatar: "assets/img/a-default.png"

# Build settings
highlighter: rouge
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

analytics:
  ga4_property: 2LQTSHXN9V
